# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x08services\" \n\x0bJsonRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\"C\n\x0cJsonResponse\x12\x11\n\tjson_data\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2J\n\x08Service1\x12>\n\x0bProcessData\x12\x15.services.JsonRequest\x1a\x16.services.JsonResponse\"\x00\x32J\n\x08Service2\x12>\n\x0bProcessData\x12\x15.services.JsonRequest\x1a\x16.services.JsonResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSONREQUEST']._serialized_start=27
  _globals['_JSONREQUEST']._serialized_end=59
  _globals['_JSONRESPONSE']._serialized_start=61
  _globals['_JSONRESPONSE']._serialized_end=128
  _globals['_SERVICE1']._serialized_start=130
  _globals['_SERVICE1']._serialized_end=204
  _globals['_SERVICE2']._serialized_start=206
  _globals['_SERVICE2']._serialized_end=280
# @@protoc_insertion_point(module_scope)
